<?php
// application level variables
define('DEBUG', false);
define('GENERATE_QR_CODE', false); // generates and saves image to hd

if( DEBUG ):
    ini_set ('display_errors', 'true');
    error_reporting(E_ALL);
endif;

require_once('Google2FA.php');

$InitalizationKey = "";     // secret generated from qr_code.php

$form_action = 'authenticate';

if(isset($_POST['action']) && ( $_POST['action'] == $form_action )):

    // Use this to verify a key as it allows for some time drift.

    $key = $_POST['key']; // user input;

    $result = Google2FA::verify_key($InitalizationKey, $key);

endif;

$page_title = "Google TOTP Two-factor Authentication for PHP";
$page_description = "Demonstration and source code of Google TOTP Two-factor Authentication for PHP";
$menu2_class = "active";
require_once('template-top.php'); 
require_once('nav-top.php'); 
?>
<html>
    <head>
        <title>Google OTP Authenticator</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <form name="qr_code_inputs" method="post">
            <input type="hidden" name="action" value="<?php echo $form_action; ?>" />
            <div class="form-group">
                <label for="key">Key:</label> <input name="key" value="" placeholder="Enter your key" class="form-control" />
                <p class="help-block">Enter the key generated by the Google authenticator.</p>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <?php if( isset($result)): ?>
        <p><?php if( $result ): ?><strong>Correct!</strong><?php else: ?><strong>Incorrect :-(</strong><?php endif; ?></p>
        <?php endif; ?>
<?php require_once('template-bottom.php'); ?>